### ISSUE TITLE
 No such file or directory: 'gpt2.bin'

### ISSUE THREAD

**Issue by mkava98** [dx-dtran/gpt2-vision#3]
Hi, I wanna run your code but I have an error " No such file or directory: 'gpt2.bin'".
how can I download this file?
what's your email address?

**Comment by dx-dtran** [comment]
hi @mkava98 thanks, please download the 3 weights files (gpt2.pt, clip.pt, vl_connector.pt) from my hugging face link described at the bottom of the readme here: https://github.com/dx-dtran/gpt2-vision?tab=readme-ov-file#train

place the weights file in the same directory as the code

I fixed the code to properly point to those weight files via #4 

The code should work after downloading the weights

**Comment by mkava98** [comment]
Thanks for your help! 
I grabbed the weight files, and the code is working great.
I appreciate you taking the time to sort this out.
